# Site settings
email: audiebantzhan@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/-:num"
google_analytics: UA-85646315-1

# SEO
title: Audiebant
aphorisme: "笋因落箨方成竹，鱼为奔波始化龙"
description: Android Developer
url: "/images/profile/img_me.jpg"

twitter_username: ZhanAudiebant
default_img: http://area.sinaapp.com/bingImg

# Profile settings
name: Zhan Audiebant
profile_img: "/images/profile/img_me.jpg"
profile: Android Devoloper. This is my personal blog and any views expressed here are mine.
social:
  github: https://github.com/audiebantzhan
  twitter: https://twitter.com/ZhanAudiebant
  weibo: http://weibo.com/audiebant
  rss: /feed.xml

# Build settings
include: ["_categories"]
exclude: ["_screenshots","Gemfile", "Gemfile.lock"]
permalink: /:year/:month/:day/:title/

# Format
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

kramdown:
  input: GFM

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
